Replaced stats pkg with stats-go lib
motiv-labs/janus pull request #103
Opened 2017-03-17 15:54 UTC by vgarvardt

Refers https://github.com/hellofresh/janus/issues/78

Must be merged only after https://github.com/hellofresh/automation/pull/1053 to avoid stats ID flood

2017-03-19 20:29 UTC, italolelis requested changes

2017-03-19 20:29 UTC, italolelis commented on ci/assets/docker-compose.yml
> +        STATSD_DSN: ''
I prefer to remove it if it's not gonna be used. Also the behaviour of statsd should be explicit mentioned on the docs.

2017-03-20 10:35 UTC, vgarvardt commented on ci/assets/docker-compose.yml
> +        STATSD_DSN: ''
Removed from compose, added docs

2017-03-20 16:08 UTC, italolelis approved these changes

2017-03-20 16:08 UTC, italolelis commented
👍

2017-03-20 16:47 UTC, merged