Configuration hot reload
motiv-labs/janus pull request #120
Opened 2017-04-05 00:06 UTC by italolelis

## What does this PR do?

* Adds the ability to hot reload proxy definitions. To enable this feature you MUST use Redis as your datastore. If you use in memory storage this feature will not be enabled.
* Adds a bunch of tests.
* Added the ability to enable or disable plugins per API definitions. This will bring us a lot of flexibility in developing new plugins and hooking them up. This feature is a BC and we should upgrade the major version because of that. 
* Using viper to load the API definitions when using file based configurations. This allows you to configure your API definitions in YAML, JSON and TOML.

2017-04-05 08:43 UTC, vgarvardt requested changes

2017-04-05 08:43 UTC, vgarvardt commented on pkg/api/api_test.go
> +package api_test
wrong package?

2017-04-05 08:43 UTC, vgarvardt commented on pkg/api/api_test.go
> +func TestNewInstanceOfDefinition(t *testing.T) {
IntelliJ Gogland suggest the following names for tests (and I like it, although it is not necessary):
* `Test<FunctionName>()` for functions
* `Test<StructName>_<MethodName>()` for struct methods

With the naming like this it is easier to track what it tests.

2017-04-05 08:43 UTC, vgarvardt commented on pkg/api/file_repository.go
> +			log.Debug("API configuration changed, reloading...")
`log.WithFields(log.Fields("name": e.Name, "op": e.Op.String()}).Debug("API configuration changed, reloading...")`

2017-04-05 08:43 UTC, vgarvardt commented on pkg/api/file_repository.go
> +			if err := v.Unmarshal(definition); err != nil {
`e.Op` can be `Remove`, then no need to unmarshal, or `Rename`, then I do not know if `viper` handles this properly and re-reads new file. I think you should leave only logging part for now and implement this in `hot-reload` feature.

2017-04-05 08:43 UTC, vgarvardt commented on pkg/loader/api_loader.go
> +		logger.WithField("errors", err.Error()).Warn("Validation errors")
`WithError(err)`

2017-04-05 08:43 UTC, vgarvardt commented on pkg/loader/api_loader.go
> +				logger.Debugf("Plugin %s enabled", pName)
`logger.WithField("name", pName).Debug("Plugin enabled")`

2017-04-05 08:43 UTC, vgarvardt commented on pkg/loader/api_loader.go
> +				logger.Debugf("Plugin %s not enabled", pName)
`logger.WithField("name", pName).Debug("Plugin not enabled") `

2017-04-05 08:43 UTC, vgarvardt commented on pkg/loader/api_loader.go
> +		logger.Warn("API URI is invalid or not active, skipping...")
I think we should add `WithError(err)` here, then it will clear in log if it is invalid or not active

2017-04-05 08:43 UTC, vgarvardt commented on pkg/loader/api_loader_test.go
> +package loader_test
`package loader`

2017-04-05 08:43 UTC, vgarvardt commented on pkg/middleware/host_matcher_test.go
> +package middleware_test
`package middleware`

2017-04-05 08:43 UTC, vgarvardt commented on pkg/middleware/logger_test.go
> +package middleware_test
`package middleware`

2017-04-05 08:43 UTC, vgarvardt commented on pkg/middleware/opentracing_test.go
> +package middleware_test
`package middleware`

2017-04-05 08:43 UTC, vgarvardt commented on pkg/middleware/rate_limit_logger_test.go
> +package middleware_test
`package middleware`

2017-04-05 08:43 UTC, vgarvardt commented on pkg/middleware/recovery_test.go
> +package middleware_test
`package middleware`

2017-04-05 08:43 UTC, vgarvardt commented on pkg/middleware/stats_test.go
> +package middleware_test
`package middleware`

2017-04-05 08:43 UTC, vgarvardt commented on pkg/oauth/file_repository.go
> +			log.Debug("OAauth2 configuration changed, reloading...")
same comments as for routes hot reloading

2017-04-05 10:23 UTC, italolelis commented on pkg/api/api_test.go
> +package api_test
nope. This is the test suffix only... This makes sure that you don't load test functions to your binary when compiling

2017-04-05 10:29 UTC, italolelis commented on pkg/loader/api_loader_test.go
> +package loader_test
it's `loader_test`

2017-04-05 19:57 UTC, rafaeljesus commented on pkg/store/store.go
> +// form an update
typo `from`

2017-04-06 12:30 UTC, vgarvardt requested changes

2017-04-06 12:30 UTC, vgarvardt commented on docs/plugins/rate_limit.md
> +| limit         | Defines the limit rule for the proxy. i.e. "10-S", means 10 req/s
I could not find format for this field, only one sample in description for `10 req/s`. How do I do `15 req/min`, `100 req/h`, `10000 req/day`? If this supports only `req/s` then `-S` suffix is redundant, if it supports all types of limits that I mentioned - we need a description for this or a link to a format description.

2017-04-06 12:30 UTC, vgarvardt commented on README.md
> +The simplest way of installing janus is to run the docker image for it. Just check the [docker-compose.yml](docker-compose.yml)
All other docs has `janus` capitalised.

2017-04-06 12:30 UTC, vgarvardt commented on docs/quick_start/auth.md
> +To start using the Janus adminstration API you need to get a [Json Web Token](https://jwt.io) and provide it in every single request
`JSON` is an abbreviation, so all letters must be capital.

2017-04-06 12:30 UTC, vgarvardt commented on pkg/loader/oauth_loader.go
> +		if m.subs != nil {
Add some log here, like `log.WithField("name", oauthServer.Name).Debug("Registering OAuth server")` and same to the end of the registering the server process.

2017-04-06 12:30 UTC, vgarvardt commented on pkg/oauth/middleware_revoke.go
> +// If you configure Janus to use a datastore and you are not suing JWT as
not *using* JWT

2017-04-06 12:30 UTC, vgarvardt commented on pkg/oauth/middleware_secret.go
>  // ChangeRequest modifies the request to add the Authorization headers.
method name changed, but doc not

2017-04-06 12:30 UTC, vgarvardt commented on pkg/plugin/rate_limit.go
> +func (h *RateLimit) getLimmiterStore(policy string, prefix string) (limiter.Store, error) {
*getLim~~m~~iterStore*

2017-04-06 12:40 UTC, italolelis commented on docs/config/proxy.md
> +| hosts                 | Defines which [hosts](/docs/proxy/request_http_header.md) are enabled for this proxy   |
Yes the document is correct. Naming could be improved latter

2017-04-07 10:47 UTC, vgarvardt requested changes

2017-04-07 10:47 UTC, vgarvardt commented on cmd/janus/init.go
> +func initStatsdClient(config config.Stats) *stats.StatsdClient {
use `stats.Client` interface instead of `StatsdClient` implemerntation

2017-04-07 10:47 UTC, vgarvardt commented on cmd/janus/init.go
> +	client := stats.NewStatsdClient(config.DSN, config.Prefix)
`client, err := stats.NewClient(config.DSN, config.Prefix)` - currently `err` is always `nil`, but may change in the future with new backends

2017-04-07 13:00 UTC, vgarvardt commented on docs/SUMMARY.md
> +    * [CORS](plugins/cors.md)
looks like you missed `compression` plugin here and in `plugins/compression.md`

2017-04-07 14:04 UTC, vgarvardt commented
👍

2017-04-07 14:04 UTC, vgarvardt approved these changes

2017-04-07 14:04 UTC, merged