Feature/integration tests
motiv-labs/janus pull request #147
Opened 2017-05-31 16:10 UTC by vgarvardt

* Integration cucumber-like tests
* Fixed some API endpoints while working on tests - `Location` header for registering new proxies, error handling and error codes for several API calls
* Added custom `prefix` support for `redis` storage and some docs on this

2017-05-31 16:22 UTC, rafaeljesus commented on pkg/api/error.go
> +	ErrAPINameExists = errors.New(http.StatusConflict, "api name is already registered")
👍

2017-05-31 16:26 UTC, italolelis requested changes
Can we run these tests on travis?

2017-05-31 16:26 UTC, italolelis commented on docs/quick_start/storage.md
> +Some Janus functionality requires key/value storage. This functionality is:
`This functionalities are`

2017-05-31 16:32 UTC, rafaeljesus commented on pkg/api/repository.go
> +type Repository interface {
👍

2017-05-31 16:34 UTC, rafaeljesus approved these changes

2017-05-31 16:36 UTC, rafaeljesus commented
That issue regarding `COVERALLS_TOKEN` again on travis

2017-05-31 16:36 UTC, italolelis commented
@rafaeljesus it's not that issue, it's something else

2017-05-31 16:39 UTC, vgarvardt commented
Yes, I can reproduce locally - problem with `overalls` failing to process `godog_test.go` in project root. Trying to fix this.

2017-06-01 15:01 UTC, vgarvardt commented
Fixed `overalls` issue and one more I found with `chi`.

@italolelis running theses tests on travis is possible, but requires some more work. There are two things that should be solved:
* run `docker-compose` in travis environment, that does not seem to be big problem - https://elliot.land/post/using-docker-compose-on-travis-ci
* run travis build after new release is built or build artifact after successful unit tests and run integration tests against this artifact

2017-06-01 16:25 UTC, italolelis approved these changes

2017-06-01 16:25 UTC, italolelis commented
👍

2017-06-01 16:31 UTC, merged