Feature/checker
motiv-labs/janus pull request #153
Opened 2017-06-21 17:38 UTC by italolelis

## What does this PR do?
- Updated logrus version
- Added health-go to be used as our health check package
- Added Healthcheck to dockerfile
- Removed logstash formatter
- Added wiremock instead of actual hosts
- Added more tests

2017-06-26 09:56 UTC, vgarvardt requested changes

2017-06-26 09:56 UTC, vgarvardt commented on pkg/loader/api_loader_test.go
> +	register := proxy.NewRegister(r, proxy.Params{StatsClient: stats.NewStatsdClient("", "")})
use `stats.NewClient("memory://", "")` in tests - see https://github.com/hellofresh/stats-go#usage-in-unit-tests for details

2017-06-26 09:56 UTC, vgarvardt commented on pkg/loader/loader_test.go
> +			StatsClient: stats.NewStatsdClient("", ""),
use `stats.NewClient("memory://", "")` in tests - see https://github.com/hellofresh/stats-go#usage-in-unit-tests for details

2017-06-26 09:56 UTC, vgarvardt commented on pkg/proxy/register.go
> +			log.Debugf("Stripping listen path: %s", listenPath)
do not use `log.<level>f()` -> `log.WithField(...).WithFields(...).<level>("<Static message>")`

in this case it is going to be `log.WithField("path", listenPath).Debug("Stripping listen path")`

2017-06-26 09:56 UTC, vgarvardt commented on pkg/proxy/register_test.go
> +		StatsClient: stats.NewStatsdClient("", ""),
use `stats.NewClient("memory://", "")` in tests - see https://github.com/hellofresh/stats-go#usage-in-unit-tests for details

2017-06-26 10:08 UTC, vgarvardt approved these changes

2017-06-26 13:58 UTC, vgarvardt commented
👍

2017-06-26 14:59 UTC, rafaeljesus commented on pkg/checker/checker.go
> +		resp, err := http.DefaultClient.Do(req)
Take a 👀 at [here](https://github.com/hellofresh/signin-service/blob/master/pkg/checker/auth_service.go) to avoid too many open files issue

2017-06-26 15:07 UTC, rafaeljesus commented on pkg/proxy/register.go
> +		log.Debug(a + b)
Maybe add a description/text on the debug message

2017-06-26 15:11 UTC, rafaeljesus commented on pkg/proxy/transport.go
> +			for {
If no more statements is expected here, you could just range over it:
```go
for range time.After(o.CloseIdleConnsPeriod) {
  tr.CloseIdleConnections()
}
```

2017-06-27 20:10 UTC, rafaeljesus commented on pkg/checker/checker.go
> +		// Inform auth-service to close the connection after the transaction is complete
`auth-service`

2017-06-27 20:15 UTC, rafaeljesus commented on pkg/checker/checker.go
> +		// Inform auth-service to close the connection after the transaction is complete
`auth-service`

2017-06-27 21:13 UTC, vgarvardt commented on Dockerfile
> +ADD dist/healthchecker-linux-amd64 /
Where does this binary comes from?

2017-06-29 08:57 UTC, rafaeljesus commented
👍

2017-06-29 09:12 UTC, rbnunes commented
+1

2017-06-29 10:36 UTC, merged