Feature/plugin restructure
motiv-labs/janus pull request #159
Opened 2017-06-30 14:44 UTC by italolelis

## What does this PR do?

- Changed how our plugin architecture works. This will allow us in the future to move to go plugins natively (once they start supporting more platforms)
- Added more tests for plugins
- Added docs for plugins
- Added more examples on how to use Janus in many different ways

2017-06-30 19:31 UTC, rafaeljesus commented on docs/quick_start/add_plugins.md
> +Let's create a file called `rate_limit.json` with our new additions to the API definition. We will create a rate limit rula that we can only send `5 req/m`
typo `rula`

2017-06-30 19:33 UTC, rafaeljesus commented on docs/quick_start/add_plugins.md
> +http -v PUT localhost:8081/apis/my-endpoint "Authorization:Bearer yourToken" "Content-Type: application/json" < rate_limit.json
We need to expose `PATCH` method for changing proxies and use `PUT` for update the whole thing

2017-06-30 19:35 UTC, rafaeljesus commented on docs/quick_start/add_plugins.md
> +This means the plugin is working properly. Now lets make the same requet 4 more times... On the fith time you should get:
typo `requet` and `fith`

2017-06-30 19:36 UTC, rafaeljesus commented on examples/front-proxy-auth/apis/example.json
> +                {
Indentation of `{`

2017-06-30 19:52 UTC, rafaeljesus requested changes
Some typos, after that it's ready to go

2017-07-03 09:02 UTC, rafaeljesus approved these changes

2017-07-03 09:03 UTC, rafaeljesus commented
👍 🚀

2017-07-04 10:15 UTC, italolelis commented
👍

2017-07-04 10:45 UTC, vgarvardt commented
@italolelis +1 once more plz, I pushed one more tiny commit

2017-07-04 11:39 UTC, italolelis commented
👍

2017-07-04 11:44 UTC, italolelis commented
Ow I just realized... It's my PR. @vgarvardt can you +1?

2017-07-04 12:03 UTC, vgarvardt commented
👍

2017-07-04 12:03 UTC, merged

2017-07-04 12:09 UTC, rafaeljesus commented
👍