Balancer not working
motiv-labs/janus pull request #242
Opened 2017-11-21 17:31 UTC by rafaeljesus

Fix load balancer not working

2017-11-21 18:14 UTC, italolelis requested changes

2017-11-21 18:14 UTC, italolelis commented on pkg/proxy/register.go
> +			return err
I would do `errors.Wrap(err, "Could not create a balancer")`

2017-11-21 18:14 UTC, italolelis commented on pkg/proxy/register.go
> +		if proxyDefinition.IsBalancerDefined() {
I would just check for `if balancer != nil {` since you set the balancer before

2017-11-21 18:14 UTC, italolelis commented on pkg/proxy/register.go
>  		// TODO: find better solution
Is this comment still necessary?

2017-11-21 18:16 UTC, italolelis commented on pkg/proxy/register.go
> +			return err
And from `"github.com/pkg/errors"`

2017-11-22 09:11 UTC, vgarvardt commented
👍

2017-11-22 09:57 UTC, italolelis approved these changes

2017-11-22 14:33 UTC, merged