Added store unit sets
motiv-labs/janus pull request #71
Opened 2017-02-07 13:48 UTC by vgarvardt

2017-02-07 22:48 UTC, italolelis requested changes

2017-02-07 22:48 UTC, italolelis commented on pkg/store/redis.go
> +	mockGetConnection func() redis.Conn
This really doesn't feel right... having a mocking method on a struct.
Probably better to have an `TestingStore` where you can mock the `GetConnection` method

2017-02-08 08:19 UTC, vgarvardt commented on pkg/store/redis.go
> +	mockGetConnection func() redis.Conn
Removed mock method and extracted all logic to private methods that are tested now.

2017-02-27 10:01 UTC, vgarvardt commented
Updated PR to reflect the latest changes from https://github.com/hellofresh/janus/pull/85

2017-03-17 14:18 UTC, italolelis approved these changes

2017-03-17 14:18 UTC, italolelis commented
👍

2017-03-17 14:26 UTC, merged