Track muted stats in logs
motiv-labs/janus pull request #77
Opened 2017-02-16 16:10 UTC by vgarvardt

After merging I suggest to disable stats collecting in teams staging and, maybe, on global staging as it takes to much space in graphite - today I removed `7.5GB` staging counters and `4.2GB` staging timers data from graphite as it run out of free space again.

2017-02-16 16:29 UTC, italolelis requested changes

2017-02-16 16:29 UTC, italolelis commented on cmd/janus/main.go
> +	statsClient := stats.NewStatsClient(statsdClient, globalConfig.Statsd.DSN == "")
I understand the motivation of doing this and I agree that we should have it, just the implementation that is not really nice. If we create an interface for the `StatsClient` we could have the real `StatsClient` and if `globalConfig.Statsd.DSN == ""` we would use the `MutedClient` that only logs (strategy pattern), this way we wouldn't need to change the contract to have mute option that makes it not really clear.

2017-02-16 18:12 UTC, vgarvardt commented on cmd/janus/main.go
> +	statsClient := stats.NewStatsClient(statsdClient, globalConfig.Statsd.DSN == "")
I want Live and Muted clients to produce the same metrics, so I generalised incrementer and time tracker.

2017-02-17 10:59 UTC, vgarvardt commented on cmd/janus/main.go
> +	statsClient := stats.NewStatsClient(statsdClient, globalConfig.Statsd.DSN == "")
Incapsulated statsd into stats completely

2017-02-17 11:39 UTC, italolelis requested changes

2017-02-17 11:39 UTC, italolelis commented on cmd/janus/init.go
> +		muted = true
If you do `statsd.Mute` you already have the value... I think the `muted` extra var is unecessary

2017-02-27 14:21 UTC, vgarvardt commented
Extracted this code to separate `stats` package. Will be released soon and will replace stats package in the code base.

2017-02-27 14:21 UTC, closed without merging